name: neom_core
description: Core for Open Neom Modules.
version: 2.1.2-dev
homepage: https://github.com/Open-Neom/neom_core

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^5.0.0-release-candidate-9.3.2

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  cloud_functions: ^6.0.5
  firebase_storage: ^13.0.4
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  firebase_crashlytics: ^5.0.5
  googleapis_auth: ^2.0.0

  logger: ^2.6.2
  http: ^1.6.0
  hive_flutter: ^1.1.0

  enum_to_string: ^2.2.1
  path_provider: ^2.1.5

  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  google_api_headers: ^5.0.1
  neom_maps_services: ^2.0.0
  neom_google_places: ^2.0.1

  upgrader: ^12.1.0
  package_info_plus: ^9.0.0

  in_app_purchase: ^3.2.3

  rxdart: ^0.28.0
  in_app_purchase_android: ^0.4.0+7
  in_app_purchase_storekit: ^0.4.6+2
  html: ^0.15.6
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
