name: neom_core
description: Core for Open Neom Modules.
version: 1.4.0
homepage: https://github.com/Cyberneom/neom_core
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^5.0.0-release-candidate-9.3.2

  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1
  firebase_storage: ^12.4.6
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  firebase_crashlytics: ^4.3.6
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  googleapis_auth: ^2.0.0
  permission_handler: ^12.0.0+1

  logger: ^2.5.0
  url_launcher: ^6.3.1
  http: ^1.4.0
  hive_flutter: ^1.1.0

  rflutter_alert: ^2.0.7
  enum_to_string: ^2.2.1
  path_provider: ^2.1.5

  cached_network_image: ^3.4.1

  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.1
  google_api_headers: ^4.4.5
  neom_maps_services: ^1.0.3
  neom_google_places: ^1.0.1

  upgrader: ^11.4.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
