name: neom_commons
description: Commons for Cyberneom.
version: 1.3.0
homepage: https://github.com/Cyberneom/neom_commons
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^5.0.0-release-candidate-9.3.2

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  lucide_icons_flutter: ^3.0.0
#  transparent_image: ^2.0.1

  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5

  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  permission_handler: ^12.0.0+1

  crypto: ^3.0.6

  url_launcher: ^6.3.1
  http: ^1.3.0

  hive_flutter: ^1.1.0

  logger: ^2.5.0
  rflutter_alert: ^2.0.7
  enum_to_string: ^2.2.1
  path_provider: ^2.1.5

  cached_network_image: ^3.4.1

  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.1
  google_api_headers: ^4.4.3
  neom_maps_services: ^1.0.3
  neom_google_places: ^1.0.1

  intl: ^0.20.2
  readmore: ^3.0.0
  animated_text_kit: ^4.2.3

  uuid: ^4.5.1

  google_fonts: ^6.2.1
  html: ^0.15.6
  percent_indicator: ^4.2.5
  flutter_rating_bar: ^4.0.1

  #events | booking
  carousel_slider: ^5.0.0
  flutter_slider_indicator: ^1.0.0
  rubber: ^1.1.0

  #admin | onboarding | commerce
  intl_phone_field: ^3.2.0

  upgrader: ^11.0.0
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0

  #events |
  in_app_purchase: ^3.2.1

  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.18.6

  #ANALYTICS & STATS
  csv: ^6.0.0
  fl_chart: ^0.71.0
  flutter_animate: ^4.5.2

#NOT IN USE
# in_app_review: ^2.0.10
# flutter_localization: ^0.2.0
# on_audio_query: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
